---
- name: Playbook to configure event driven ansible controller post installation
  hosts: all
  connection: local
  gather_facts: false

  tasks:

    - name: Include vars from configs directory
      ansible.builtin.include_vars:
        dir: "{{ controller_configs_dir | default('.configs') }}"
        ignore_files: [controller_config.yml.template]
        extensions: ["yml"]
      tags:
        - always

    - name: Call dispatch role
      ansible.builtin.include_role:
        name: infra.eda_configuration.dispatch
