---
- name: Configure Automation Controller
  hosts: 127.0.0.1
  connection: local
  gather_facts: false

  vars:
    controller_configuration_instance_groups_enforce_defaults: true
    controller_configuration_credentials_secure_logging: false

  tasks:
    - name: Include vars from configs directory
      ansible.builtin.include_vars:
        dir: "{{ controller_configs_dir | default('./configs') }}"
        ignore_files: [controller_config.yml.template]
        extensions: ["yml"]
      tags:
        - always

    - name: Call all roles
      ansible.builtin.include_role:
        name: infra.controller_configuration.dispatch

