---
controller_credentials: 

  - name: ansible-vault Key
    description: 'This key is used to decrypt the files in the project ecrypted with ansible-vault.'
    organization: Default
    credential_type: Vault
    inputs:
      vault_password: "{{ ansible_vault_key }}"

  - name: SCM dummy
    description: ''
    organization: Default
    credential_type: Source Control
    inputs:
      username: nzansiblet1dsa
      password: "dummy"

  - name: Controller Credential
    description: ''
    organization: Default
    credential_type: Red Hat Ansible Automation Platform
    inputs: 
      host: "{{ controller_hostname }}"
      verify_ssl: false
      username: "{{ controller_username }}"
      password: "{{ controller_password }}"

  - name: AWS
    credential_type: Amazon Web Services
    organization: Default
    update_secrets: false
    state: exists
    inputs:
      username: "{{ aws_console_username }}"
      password: "{{ aws_console_password }}"

  - name: Linux Machine
    description: ''
    organization: Default
    credential_type: Machine
    inputs: 
      username: "{{ machine_username }}"
      password: "{{ machine_password }}"
      become_method: sudo
      become_password: "{{ machine_become_password }}"
      