# controller_inventory_sources:
#   - name: AWS Inventory
#     organization: Default
#     source: ec2
#     inventory: Demo Inventory
#     credential: AWS
#     overwrite: true
#     source_vars:
#       hostnames:
#         - tag:Name
#       compose:
#         ansible_host: public_ip_address
#         ansible_user: 'ec2-user'
#       groups:
#         cloud_aws: true
#         os_linux: tags.blueprint.startswith('rhel')
#       keyed_groups:
#         - key: platform
#           prefix: os
#         - key: tags.blueprint
#           prefix: blueprint
#         - key: tags.owner
#           prefix: owner