---
controller_projects:
  - name: Compliance_Digital_Twin_Project
    organization: Default
    scm_branch: 'main'
    credential: 'SCM dummy'
    scm_clean: 'no'
    scm_delete_on_update: 'no'
    scm_type: git
    scm_update_on_launch: 'no'
    scm_url: "{{ project_repo_url }}"