---
controller_projects:
  - name: Compliance_Digital_Twin_Project
    organization: Default
    scm_branch: 'main'
    credential: 'SCM dummy'
    scm_clean: 'no'
    scm_delete_on_update: 'no'
    scm_type: git
    scm_update_on_launch: 'no'
    scm_url: "{{ project_repo_url }}"
    allow_override: 'yes'

  - name: Compliance_Digital_Twin_Project [DEVEL]
    organization: Default
    scm_branch: 'devel'
    credential: 'SCM dummy'
    scm_clean: 'no'
    scm_delete_on_update: 'no'
    scm_type: git
    scm_update_on_launch: 'no'
    scm_url: "{{ project_repo_url }}"
    allow_override: 'yes'

  - name: Ansible Cloud Content Lab - AWS
    organization: Default
    scm_type: git
    wait: true
    scm_url: https://github.com/sonstar2/aws.infrastructure_config_demos.git
    default_environment: Cloud Services Execution Environment