# ---
# eda_credentials:
#   - name: AAPNew
#     description: AAP Controller Credential
#     credential_type_name: 'Red Hat Ansible Automation Platform'
#     organization_name: Default
#     inputs:
#       host: "{{ controller_api }}"
#       username: "{{ controller_username }}"
#       secret: "{{ controller_password }}"
#       verify_ssl: false

