---
# eda_credentials:
#   - name: AAPNew
#     description: AAP Controller Credential
#     credential_type: 'Red Hat Ansible Automation Platform'
#     host: "{{ controller_api }}"
#     username: "{{ controller_username }}"
#     secret: "{{ controller_password }}"

